import type { DeckPilotConfig } from "shared";

export const defaultConfig: DeckPilotConfig = {
  version: 8,
  server: { port: 9900, host: "0.0.0.0" },
  activeProfile: "default",
  profiles: [
    {
      id: "default",
      name: "Default",
      grid: { columns: 5, rows: 3 },
      pageGridSize: { rows: 1, cols: 4 },
      pages: [
        {
          id: "main",
          name: "Main",
          gridPosition: { row: 0, col: 0 },
          widgets: [
            // Row 0: Volume slider (3 cols), Mute, Play/Pause
            {
              id: "vol-slider",
              type: "slider",
              label: "Volume",
              color: "#3b82f6",
              position: { row: 0, col: 0, colspan: 3 },
              sliderAction: { type: "audio.volume_set", params: { level: 0 } },
              min: 0,
              max: 100,
              step: 1,
            },
            {
              id: "mute",
              type: "button",
              label: "Mute",
              icon: "volume-mute",
              color: "#ef4444",
              action: { type: "audio.mute", params: {} },
              position: { row: 0, col: 3 },
            },
            {
              id: "play-pause",
              type: "button",
              label: "Play",
              icon: "play",
              color: "#22c55e",
              action: { type: "media.play_pause", params: {} },
              position: { row: 0, col: 4 },
            },
            // Row 1-2: Spotify Now Playing (3 cols, 2 rows) + app launchers
            {
              id: "spotify-np",
              type: "now_playing",
              label: "Now Playing",
              color: "#1db954",
              position: { row: 1, col: 0, colspan: 3, rowspan: 2 },
              dataSource: "spotify",
            },
            {
              id: "browser",
              type: "button",
              label: "Safari",
              icon: "globe",
              color: "#f59e0b",
              action: { type: "system.launch_app", params: { app: "Safari" } },
              position: { row: 1, col: 3 },
            },
            {
              id: "terminal",
              type: "button",
              label: "Terminal",
              icon: "terminal",
              color: "#6366f1",
              action: { type: "system.launch_app", params: { app: "Terminal" } },
              position: { row: 1, col: 4 },
            },
            {
              id: "finder",
              type: "button",
              label: "Finder",
              icon: "folder",
              color: "#06b6d4",
              action: { type: "system.launch_app", params: { app: "Finder" } },
              position: { row: 2, col: 3 },
            },
            {
              id: "say-hi",
              type: "button",
              label: "Say Hi",
              icon: "message",
              color: "#a855f7",
              action: { type: "exec.applescript", params: { script: 'say "Hello from DeckPilot"' } },
              position: { row: 2, col: 4 },
            },
          ],
        },
        {
          id: "system",
          name: "System",
          gridPosition: { row: 0, col: 1 },
          widgets: [
            {
              id: "sys-cpu-gauge",
              type: "now_playing" as const,
              label: "CPU",
              color: "#3b82f6",
              position: { row: 0, col: 0 },
              dataSource: "system_stats",
              variant: "gauge",
              widgetProps: { metric: "cpu" },
            },
            {
              id: "sys-mem-gauge",
              type: "now_playing" as const,
              label: "Memory",
              color: "#22c55e",
              position: { row: 0, col: 1 },
              dataSource: "system_stats",
              variant: "gauge",
              widgetProps: { metric: "memory" },
            },
            {
              id: "sys-bat-gauge",
              type: "now_playing" as const,
              label: "Battery",
              color: "#f59e0b",
              position: { row: 0, col: 2 },
              dataSource: "system_stats",
              variant: "gauge",
              widgetProps: { metric: "battery" },
            },
            {
              id: "sys-disk-gauge",
              type: "now_playing" as const,
              label: "Disk",
              color: "#a855f7",
              position: { row: 0, col: 3, colspan: 2 },
              dataSource: "system_stats",
              variant: "bar",
              widgetProps: { metric: "disk" },
            },
            {
              id: "sys-cpu-ts",
              type: "now_playing" as const,
              label: "CPU History",
              color: "#3b82f6",
              position: { row: 1, col: 0, colspan: 3, rowspan: 2 },
              dataSource: "system_stats",
              variant: "timeseries",
              widgetProps: { metric: "cpu" },
            },
            {
              id: "sys-mem-bar",
              type: "now_playing" as const,
              label: "Memory",
              color: "#22c55e",
              position: { row: 1, col: 3, colspan: 2 },
              dataSource: "system_stats",
              variant: "bar",
              widgetProps: { metric: "memory" },
            },
            {
              id: "sys-discord",
              type: "now_playing" as const,
              label: "Discord",
              color: "#5865F2",
              position: { row: 2, col: 3, colspan: 2 },
              dataSource: "discord",
            },
          ],
        },
        {
          id: "sounds",
          name: "Sounds",
          gridPosition: { row: 0, col: 2 },
          widgets: [
            {
              id: "soundboard",
              type: "soundboard",
              label: "Soundboard",
              color: "#f59e0b",
              position: { row: 0, col: 0, colspan: 5, rowspan: 3 },
              dataSource: "soundboard",
            },
          ],
        },
        {
          id: "setup",
          name: "Setup",
          gridPosition: { row: 0, col: 3 },
          widgets: [
            {
              id: "setup-title",
              type: "spacer",
              label: "",
              position: { row: 0, col: 0, colspan: 5 },
            },
            {
              id: "copy-udev",
              type: "button",
              label: "Fix Gamepad (udev)",
              icon: "clipboard",
              color: "#22c55e",
              action: {
                type: "clipboard.copy",
                params: {
                  text: "flatpak --user override --filesystem=/run/udev:ro com.google.Chrome",
                },
              },
              position: { row: 1, col: 0, colspan: 3 },
            },
            {
              id: "copy-kiosk",
              type: "button",
              label: "Kiosk Launch Opts",
              icon: "clipboard",
              color: "#3b82f6",
              action: {
                type: "clipboard.copy",
                params: {
                  text: '--window-size=1280,800 --force-device-scale-factor=1.25 --device-scale-factor=1.25 --kiosk "http://localhost:9900"',
                },
              },
              position: { row: 1, col: 3, colspan: 2 },
            },
            {
              id: "copy-url",
              type: "button",
              label: "Server URL",
              icon: "clipboard",
              color: "#6366f1",
              action: {
                type: "clipboard.copy",
                params: { text: "http://localhost:9900" },
              },
              position: { row: 2, col: 0, colspan: 2 },
            },
            {
              id: "copy-steam-input",
              type: "button",
              label: "Steam Input: Gamepad w/ Mouse Trackpad",
              icon: "clipboard",
              color: "#f59e0b",
              action: {
                type: "clipboard.copy",
                params: { text: "Set Steam Input to: Gamepad with Mouse Trackpad" },
              },
              position: { row: 2, col: 2, colspan: 3 },
            },
          ],
        },
      ],
    },
  ],
  gamepadBindings: [
    { button: 0, kind: "server", action: { type: "media.play_pause", params: {} }, label: "Play/Pause" },
    { button: 4, kind: "client", clientAction: "nav.page.previous", label: "Previous Page" },
    { button: 5, kind: "client", clientAction: "nav.page.next", label: "Next Page" },
  ],
};
